name: test-web

on:
  push:
    # branches-ignore:
    #   - "main"
    paths:
      - ".github/workflows/test-web.yml"
      - "**"

jobs:

  test:
    name: test-web
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Get dependencies
        run: |
          yarn install

      - name: Lint
        run: |
          yarn lint

      - name: Test
        run: |
          yarn build
